// Problem 12: Highly divisible triangular number
// The sequence of triangle numbers is generated by adding the natural numbers. So the $7$<sup>th</sup> triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// Let us list the factors of the first seven triangle numbers:
// 1: 1
// 3: 1,3
// 6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that $28$ is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?

package problems

import (
	"math"
)
// HighlyDivisibleTriangularNumber finds the first triangular number with more than the specified number of divisors.
func HighlyDivisibleTriangularNumber(divisors int) int {
	n := 1
	triangleNumber := 0

	for {
		triangleNumber += n
		n++

		if countDivisors(triangleNumber) > divisors {
			return triangleNumber
		}
	}
}

// countDivisors returns the number of divisors of a given number.
func countDivisors(num int) int {
	count := 0
	sqrtNum := int(math.Sqrt(float64(num)))

	for i := 1; i <= sqrtNum; i++ {
		if num%i == 0 {
			count += 2 // i and num/i
		}
	}

	if sqrtNum*sqrtNum == num {
		count-- // Correct for a perfect square
	}

	return count
}

