// Problem 2: Even Fibonacci numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

// Link: https://projecteuler.net/problem=2


// Solution
package problems


// FibonacciSum calculates the sum of even-valued terms in the Fibonacci sequence up to the given limit.
func FibonacciSum(limit int) int { 
	a, b := 0, 1   // Initialize first two Fibonacci numbers
	sumEven := 0 // Initialize sum of even Fibonacci numbers to 0
	for b < limit { // Loop until the Fibonacci number exceeds the limit
		if b%2 == 0 {	// Check if the Fibonacci number is even
			sumEven += b	// Add the even Fibonacci number to the sum
		}	
		a, b = b, a+b 	// Update to the next Fibonacci numbers
	}
	return sumEven // Return the final sum of even Fibonacci numbers
}