# Problem 2: Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

#  Link: https://projecteuler.net/problem=2


# Solution:
def fibonacci_even_sum(limit):
    a, b = 0, 1
    sum_even = 0
    while b < limit:
        if b%2 == 0:
            sum_even += b
        a, b = b, a + b
    return sum_even